-- Real DR retailer branch locations, geocoded via Nominatim (OpenStreetMap) from
-- addresses researched against each retailer's own site / DR business directories.
-- Replaces the 2 placeholder "Sample Branch" rows seeded in earlier dev data.
delete from stores where name like '%Sample Branch%';

insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Plaza Lama - Autopista Duarte', 'Autopista Juan Pablo Duarte Km 13, Santo Domingo, República Dominicana', 18.4829732, -69.9745912 from retailers where slug = 'plaza-lama' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Plaza Lama - Nicolás de Ovando', 'Av. Nicolás de Ovando 508, Santo Domingo, República Dominicana', 18.506936, -69.8955616 from retailers where slug = 'plaza-lama' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Plaza Lama - Av. Duarte', 'Av. Juan Pablo Duarte 78, Santo Domingo, República Dominicana', 18.5056655, -69.9143452 from retailers where slug = 'plaza-lama' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Plaza Lama - Herrera', 'Av. Isabel Aguiar, Santo Domingo Oeste, República Dominicana', 18.4568427, -69.9774083 from retailers where slug = 'plaza-lama' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Plaza Lama - Santiago 27 de Febrero', 'Av. 27 de Febrero, Santiago de los Caballeros, República Dominicana', 19.4788922, -70.717454 from retailers where slug = 'plaza-lama' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - Estrella Sadhalá', 'Av. Estrella Sadhalá, Santiago, República Dominicana', 19.4675618, -70.6870608 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - Baní', 'Av. Máximo Gómez, Carretera Sánchez, Baní, Peravia, República Dominicana', 18.2777204, -70.3320746 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - Bonao', 'Av. Las Hortensias esq. calle San Martín, Bonao, Monseñor Nouel, República Dominicana', 18.9417804, -70.4112889 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - Calle Del Sol', 'Calle Del Sol 104, Santiago de los Caballeros, República Dominicana', 19.4495607, -70.6929383 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - Charles de Gaulle', 'Av. Charles de Gaulle, Santo Domingo Este, República Dominicana', 18.4779337, -69.8281577 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - Galería 360°', 'Calle Euclides Morillo 106, Arroyo Hondo, Santo Domingo, República Dominicana', 18.5043702, -69.9311058 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - Higüey', 'Calle José A. Santana, Higüey, La Altagracia, República Dominicana', 18.6131313, -68.7114484 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - La Vega', 'Av. Gregorio Rivas 183, La Vega, República Dominicana', 19.2252622, -70.5131542 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - Mella', 'Av. Mella 258, Santo Domingo, República Dominicana', 18.4817419, -69.8850052 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Sirena - Moca', 'Carretera Duarte esq. Antonio de la Maza, Moca, Espaillat, República Dominicana', 19.3944442, -70.5257565 from retailers where slug = 'sirena' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - San Vicente de Paúl', 'Av. San Vicente de Paúl, Santo Domingo Este, República Dominicana', 18.5097615, -69.8621664 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Sambil', 'Av. John F. Kennedy, Plaza Sambil, Santo Domingo, República Dominicana', 18.4831995, -69.9118407 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - San Isidro', 'Autopista San Isidro, Coral Mall, Santo Domingo Este, República Dominicana', 18.4864345, -69.8323499 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Santiago Las Colinas', 'Av. 27 de Febrero esq. calle 25, Las Colinas, Santiago, República Dominicana', 19.4785579, -70.7136109 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Santiago Plaza Alejo', 'Estrella Sadhalá 5, Santiago, República Dominicana', 19.4658252, -70.6866972 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Cotuí', 'Calle Mella 10, Cotuí, República Dominicana', 19.0395079, -70.1475012 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Bonao', 'Calle Los Santos 114, Bonao, República Dominicana', 18.9408231, -70.4006278 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - La Vega', 'Calle Núñez de Cáceres 1, San Antonio, La Vega, República Dominicana', 19.2259628, -70.528043 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - San Francisco de Macorís', 'Av. Frank Grullón 27, San Francisco de Macorís, República Dominicana', 19.2893999, -70.2479625 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Herrera', 'Av. Isabel Aguiar, Santo Domingo Oeste, República Dominicana', 18.4568427, -69.9774083 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Máximo Gómez', 'Av. Máximo Gómez, Santo Domingo, República Dominicana', 18.5055363, -69.9157803 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Galería 360', 'Av. John F. Kennedy, Plaza Galería 360, Santo Domingo, República Dominicana', 18.4933773, -69.8991179 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Independencia', 'Av. Independencia Km 10½, Santo Domingo, República Dominicana', 18.453028, -69.9242514 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Colina Centro', 'Av. Jacobo Majluta Azar, Colinas del Viento, Santo Domingo Norte, República Dominicana', 18.5577833, -69.9433609 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Villa Mella', 'Av. Hermanas Mirabal, Santo Domingo Norte, República Dominicana', 18.5308155, -69.9075063 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Abraham Lincoln', 'Av. Abraham Lincoln, Santo Domingo, República Dominicana', 18.451844, -69.922479 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Las Américas', 'Av. Marginal Las Américas, Santo Domingo Este, República Dominicana', 18.459256, -69.7228242 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Corripio - Los Alcarrizos', 'Calle San Antonio 15, Los Alcarrizos, Santo Domingo Oeste, República Dominicana', 18.5122041, -70.0595857 from retailers where slug = 'corripio' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Jumbo - Ágora Mall', 'Av. John F. Kennedy esq. Av. Máximo Gómez, Ágora Mall, Santo Domingo, República Dominicana', 18.481222, -69.9145 from retailers where slug = 'jumbo' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Jumbo - Bávaro', '8 Av. Barceló, Higüey, República Dominicana', 18.6639583, -68.4123917 from retailers where slug = 'jumbo' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'Jumbo - Bella Vista Mall', 'Av. Sarasota esq. Arrayanes y Las Caobas, Bella Vista Mall, Santo Domingo, República Dominicana', 18.4558831, -69.9401451 from retailers where slug = 'jumbo' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'PriceSmart - Los Prados', 'Av. Charles Sumner 54, Los Prados, Santo Domingo, República Dominicana', 18.4747108, -69.9598991 from retailers where slug = 'pricesmart' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'PriceSmart - Arroyo Hondo', 'Av. República de Colombia 84, Altos de Arroyo Hondo, Santo Domingo, República Dominicana', 18.5068526, -69.9599495 from retailers where slug = 'pricesmart' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'PriceSmart - San Isidro', 'Autopista San Isidro 3, Urb. Italia, Santo Domingo Este, República Dominicana', 18.4898961, -69.8421262 from retailers where slug = 'pricesmart' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'PriceSmart - Santiago', 'Av. Estrella Sadhalá 21, Santiago, República Dominicana', 19.4675618, -70.6870608 from retailers where slug = 'pricesmart' on conflict do nothing;
insert into stores (retailer_id, name, address, latitude, longitude) select id, 'PriceSmart - Bolívar', 'Av. Simón Bolívar 802, Santo Domingo, República Dominicana', 18.4631494, -69.9282759 from retailers where slug = 'pricesmart' on conflict do nothing;
